### ISSUE TITLE
Find stryker from anywhere in project folder

### ISSUE THREAD

**Issue by OlafHaalstra** [stryker-mutator/stryker-cli#14]
Nicojs told me that the stryker install can be found more easily by not looking in the folder but by using require('stryker') (see if it exists) and require.resolve('stryker') (resolve the path). This would be nice functionality since then you no longer have to be at the root of your folder to execute the stryker command.

**Comment by nicojs** [comment]
Great, if you need any help, just let us know.

**Comment by korthout** [comment]
I've looking into using require('stryker') and require.resolve('stryker'), and this works perfectly fine for finding Stryker when it is already installed (even in a different directory, as can be expected from require), but when the Stryker module cannot be found it throws a hard Error that does not seem to be caught in a try-catch block.

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'stryker'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
```

This behaviour is discussed in [this comment on stackoverflow](http://stackoverflow.com/questions/17553386/catch-an-error-on-requiring-module-in-node-js#comment25533870_17553386) as:

> `require` itself suggests that this module is essential for the app to run.

Test code:
```
try {
    const strykerPath = require.resolve('stryker');
    console.log(strykerPath);
  } catch (e) {
    if (e.code !== 'MODULE_NOT_FOUND') {
        console.log('Stryker is not yet installed');
    }
    console.log('Unexpected error caught');
    throw e;
  }
```

**Comment by avassem85** [comment]
Fixed with https://github.com/stryker-mutator/stryker-cli/pull/18
