### ISSUE TITLE
Change the repo description (remove Work in progress!)

### ISSUE THREAD

**Issue by korthout** [stryker-mutator/stryker-cli#25]
Currently the description of this repo is:
> The command line interface for Stryker (Work in progress!)

However, the CLI is now functional for stryker's installation, and for sending commands to stryker e.g. `init`. I think it's time to promote the repo from work-in-progress to something more appropriate. Which I'm sadly not able to do.

So, I propose something along the same lines as the stryker-api.
> The API for Stryker, the JavaScript mutation testing framework

For example:
The command line interface for Stryker, the JavaScript mutation testing framework

Lasty, as Stryker is now the 'The extendable JavaScript mutation testing framework.' I think we should also add extendable to both of those description. And for uniformity, I propose to remove the dot (.) at the end of the description in the main stryker repo.

**Comment by korthout** [comment]
@nicojs If you have some time, can you take a look at this?

**Comment by nicojs** [comment]
Hmm interesting. You would suggest to add "extendable" part? I later moved away from "extendable". It is a cool feature, but why not "fast" for example (an other cool feature). I would suggest to keep it simple. 

> The JavaScript mutation testing framework

**Comment by korthout** [comment]
Haha. I completely agree. I simply suggested it because it would be consistent with the description of the `stryker` repo. I suggest you choose one and make it the same everywhere. Personally, I like the simplest the best too.

**Comment by nicojs** [comment]
Ok, they're all updated i think.

**Comment by korthout** [comment]
@nicojs Thanks for the changes, one small request though. can you use `command-line interface` instead of `command line interface` in the description for the stryker-cli repo?

**Comment by nicojs** [comment]
Done :)

**Comment by korthout** [comment]
Perfect! I'll close this issue now.
