### ISSUE TITLE
CLI is not yet available as a binary

### ISSUE THREAD

**Issue by korthout** [stryker-mutator/stryker-cli#7]
The CLI is only available from the index.js file. A binary (stryker) should be build before releasing to npm

**Comment by OlafHaalstra** [comment]
Any ideas how?

**Comment by korthout** [comment]
I think we can add a bin definition to package.json

**Comment by korthout** [comment]
Cool looks like you solved it. I do think it should be renamed from stryker-cli to stryker to better find the stryker init command scheme.

**Comment by korthout** [comment]
I've also found that a global install of stryker-cli using npm i -g stryker-cli does provide the binary of the cli with the name `stryker`, but that executing it goes wrong.

```
> stryker --help
env: node\r: No such file or directory
```

**Comment by OlafHaalstra** [comment]
Fixed. Caused by CRLF line endings. We refacterod the file to have LF line endings.
